### ISSUE TITLE
Earlier versions of requests are required in the rebuild

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/requests-feedstock#29]
I am seeing requests 2.18 being pulled from `defaults` in other rebuild PRs.

**Comment by carlodri** [comment]
you need 2.18.0?

**Comment by ocefpaf** [comment]
We could identify if there is anything pinned that is causing that choice and see if we can unpin it. `2.18.0` is quite old

**Comment by SylvainCorlay** [comment]
2.18 was being pulled in the first builds of the julia feedsock rebuild.

**Comment by ocefpaf** [comment]
requests is pure python so it is unlikely that will cause any issues. Also, the julia feedstock incident was probably a temporary thing.

**Comment by carlodri** [comment]
so we can close this?

**Comment by SylvainCorlay** [comment]
Yes! Closing
