### ISSUE TITLE
security and socks extras?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/requests-feedstock#3]
Are the [`security`](https://github.com/kennethreitz/requests/blob/master/setup.py#L95) and [`socks`](https://github.com/kennethreitz/requests/blob/master/setup.py#L96) extras being build into `requests` here? If not, can they be? I’m building a downstream module that requires `requests[security]`.

**Comment by pmlandwehr** [comment]
Short answer is: no, they aren't.

**Comment by ocefpaf** [comment]
@pmlandwehr b/c we don't really have a policy on optional dependencies this issue feel between the cracks. Are you OK installing the extras by hand? Should we close this? Or is there a strong argument to add them by default?

**Comment by ocefpaf** [comment]
Closing this as stale.
