### ISSUE TITLE
Using bundled ca-certificates

### ISSUE THREAD

**Issue by pelson** [conda-forge/requests-feedstock#4]
Requests comes with its own cacerts.pem, but we have already packaged certificates in https://github.com/conda-forge/ca-certificates-feedstock/. Should we make that a run time dependency of requests, and simply symlink (on Unix) to the certificates in `$PREFIX/ssl/cacert.pem`?

**Comment by msarahan** [comment]
Yes, that seems reasonable.  FWIW, ca-certificates repackages certifi, which is itself an extraction of the certs from requests: https://github.com/certifi/python-certifi

This would be just closing the loop, I guess.

**Comment by jakirkham** [comment]
As of `requests` version `2.16.0`, `certifi` is a requirement of `requests`. This thanks to PR ( https://github.com/requests/requests/pull/4067 ), commit ( https://github.com/requests/requests/commit/628633143d5b8590b1dbdf5371fe81fb8250dffd ) specifically. So think we are ok to close this as resolved. Though feel free to correct me if I'm mistaken.
